
export const META_INFO_FLAG_OPEN_MICROFRONTENDS = 'openMicrofrontends';

export const ANNOTATION_ROLE_PERMISSIONS = 'MASHROOM_ROLE_PERMISSIONS';
export const ANNOTATION_DEFAULT_RESTRICT_VIEW_TO_ROLES = 'MASHROOM_DEFAULT_RESTRICT_VIEW_TO_ROLES';
export const ANNOTATION_PROXIES_RESTRICT_TO_ROLES = 'MASHROOM_PROXIES_RESTRICT_TO_ROLES';
export const ANNOTATION_META_INFO = 'MASHROOM_META_INFO'; // Test
