// flow-typed signature: edffcda06127c1e51df3b7528e7033d3
// flow-typed version: <<STUB>>/lodash.filter_v4.6.0/flow_v0.64.0

import {filter} from "lodash.filter";

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.filter' {
    declare type filter = (Array<any>, Object) => Array<any>;
    declare export default filter;
}
