// flow-typed signature: ca8c88906ec6f33e6219794cd1bae750
// flow-typed version: <<STUB>>/lowdb_v1/flow_v0.64.0

import {FileAsync} from "lowdb/adapters/FileAsync";

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lowdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lowdb' {
  declare module.exports: any;
}

declare module 'lowdb/adapters/Base' {
    declare class Base {
        source: string;
        defaultValue: Object;
        serialize: (Object) => string;
        deserialize: (string) => Object;
        constructor(source: string, options?: { defaultValue?: Object, serialize?: (Object) => string, deserialize?: (string) => Object }): void;
        read(): Promise<Object>;
        write(data: Object): Promise<void>;
    }

    declare export default typeof Base;
}
