// flow-typed signature: adc355018208240e67876c3af399d0d5
// flow-typed version: <<STUB>>/proper-lockfile_v4/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proper-lockfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proper-lockfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proper-lockfile/lib/adapter' {
  declare module.exports: any;
}

declare module 'proper-lockfile/lib/lockfile' {
  declare module.exports: any;
}

declare module 'proper-lockfile/lib/mtime-precision' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proper-lockfile/index' {
  declare module.exports: $Exports<'proper-lockfile'>;
}
declare module 'proper-lockfile/index.js' {
  declare module.exports: $Exports<'proper-lockfile'>;
}
declare module 'proper-lockfile/lib/adapter.js' {
  declare module.exports: $Exports<'proper-lockfile/lib/adapter'>;
}
declare module 'proper-lockfile/lib/lockfile.js' {
  declare module.exports: $Exports<'proper-lockfile/lib/lockfile'>;
}
declare module 'proper-lockfile/lib/mtime-precision.js' {
  declare module.exports: $Exports<'proper-lockfile/lib/mtime-precision'>;
}
