// flow-typed signature: 6a67e6fdfa7c0072886765dbcfa7176a
// flow-typed version: <<STUB>>/ws_v7/flow_v0.107.0

import {IncomingMessage} from 'http';
import {Socket} from 'net';
import {EventEmitter} from 'events';

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ws' {

    declare type ServerOptions = {
        host?: string,
        port?: number,
        noServer?: boolean,
        clientTracking?: boolean,
        maxPayload?: number,
    }

    declare type SendOptions = {
        compress?: boolean,
        binary?: boolean,
        mask?: boolean,
        fin?: boolean,
    }

    declare export class WebSocket extends EventEmitter {
        send(data: string, optionsOrCallback?: SendOptions | (error: ?Error) => void, callback?: (error: ?Error) => void): void;
        ping(data?: string, mask?: boolean): void;
        close(code?: number, reason?: string): void;
        terminate(): void;
    }

    declare export class Server {
        constructor(options: ServerOptions): void;
        handleUpgrade(request: IncomingMessage, socket: Socket, head: Buffer, cb: (ws: WebSocket) => void): void;
    }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ws/lib/buffer-util' {
  declare module.exports: any;
}

declare module 'ws/lib/constants' {
  declare module.exports: any;
}

declare module 'ws/lib/event-target' {
  declare module.exports: any;
}

declare module 'ws/lib/extension' {
  declare module.exports: any;
}

declare module 'ws/lib/permessage-deflate' {
  declare module.exports: any;
}

declare module 'ws/lib/receiver' {
  declare module.exports: any;
}

declare module 'ws/lib/sender' {
  declare module.exports: any;
}

declare module 'ws/lib/validation' {
  declare module.exports: any;
}

declare module 'ws/lib/websocket-server' {
  declare module.exports: any;
}

declare module 'ws/lib/websocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ws/index' {
  declare module.exports: $Exports<'ws'>;
}
declare module 'ws/index.js' {
  declare module.exports: $Exports<'ws'>;
}
declare module 'ws/lib/buffer-util.js' {
  declare module.exports: $Exports<'ws/lib/buffer-util'>;
}
declare module 'ws/lib/constants.js' {
  declare module.exports: $Exports<'ws/lib/constants'>;
}
declare module 'ws/lib/event-target.js' {
  declare module.exports: $Exports<'ws/lib/event-target'>;
}
declare module 'ws/lib/extension.js' {
  declare module.exports: $Exports<'ws/lib/extension'>;
}
declare module 'ws/lib/permessage-deflate.js' {
  declare module.exports: $Exports<'ws/lib/permessage-deflate'>;
}
declare module 'ws/lib/receiver.js' {
  declare module.exports: $Exports<'ws/lib/receiver'>;
}
declare module 'ws/lib/sender.js' {
  declare module.exports: $Exports<'ws/lib/sender'>;
}
declare module 'ws/lib/validation.js' {
  declare module.exports: $Exports<'ws/lib/validation'>;
}
declare module 'ws/lib/websocket-server.js' {
  declare module.exports: $Exports<'ws/lib/websocket-server'>;
}
declare module 'ws/lib/websocket.js' {
  declare module.exports: $Exports<'ws/lib/websocket'>;
}
