
export const PLACEHOLDER_REQUEST_URL = /\$REQUEST_URL/g;
export const PLACEHOLDER_STATUS_CODE = /\$STATUS_CODE/g;
export const PLACEHOLDER_MASHROOM_VERSION = /\$MASHROOM_VERSION/g;
export const PLACEHOLDER_I18N_MESSAGE = /\$MESSAGE\[(.*)\]/g;
