
export const CONFIG_REFRESH_TIMEOUT_SEC = 60;
export const FALLBACK_TOKEN_EXPIRE_IN_SEC = 60 * 60; // 1h

export const OICD_AUTH_DATA_SESSION_KEY = '__MASHROOM_SECURITY_OICD_AUTH_DATA';
export const OICD_REQUEST_DATA_SESSION_KEY_PREFIX = '__MASHROOM_SECURITY_OICD_REQ_DATA_';
export const OICD_USER_SESSION_KEY = '__MASHROOM_SECURITY_OICD_USER';
