
export const OICD_AUTH_DATA_SESSION_KEY = '__MASHROOM_SECURITY_OICD_AUTH_DATA';
export const OICD_REQUEST_DATA_SESSION_KEY_PREFIX = '__MASHROOM_SECURITY_OICD_REQ_DATA_';
export const OICD_USER_SESSION_KEY = '__MASHROOM_SECURITY_OICD_USER';
export const UNDEFINED_USER_NAME = 'undefined';
