/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MashroomSecuritySimpleProviderUsers {
  $schema?: any;
  users: {
    username: string;
    displayName?: string;
    email?: string;
    pictureUrl?: string;
    /**
     * The SHA256 hash of the password
     */
    passwordHash: string;
    roles?: string[];
    /**
     * Will be mapped to user.extraData
     */
    extraData?: {
      [k: string]: any;
    };
    /**
     * Will be mapped to user.secrets
     */
    secrets?: {
      [k: string]: any;
    };
    [k: string]: any;
  }[];
}
