/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Rule = "any" | string[];

export interface MashroomSecurityTopicAcl {
  $schema?: any;
  /**
   * This interface was referenced by `MashroomSecurityTopicAcl`'s JSON-Schema definition
   * via the `patternProperty` "^[a-zA-Z0-9/?#]+$".
   */
  [k: string]: {
    allow?: Rule;
    deny?: Rule;
  };
}
