
name: Mashroom CI Build

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 45

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run setup
    - run: npm run build
    - uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: packages/**/test-reports/junit.xml
        reporter: jest-junit
